import re
EPOCHS = 100
IMAGE_LENGTH = 128
IMAGE_DEPTH = 3

BATCH_SIZE = 64
KERNEL_SIZE = 2
STRIDE_SIZE = 2

NUM_ENCODER_CHANNELS = 64
NUM_Z_CHANNELS = 100
NUM_GEN_CHANNELS = 1024

NUM_AGE_GROUPS = 5
NUM_BMI_GROUPS = 3
LABEL_LEN = NUM_AGE_GROUPS + NUM_BMI_GROUPS
NUM_BMI_GROUPS_EXPANDED = NUM_BMI_GROUPS * (NUM_AGE_GROUPS // NUM_BMI_GROUPS)
LABEL_LEN_EXPANDED = NUM_AGE_GROUPS + NUM_BMI_GROUPS_EXPANDED

HEALTHY = 0
OVERWEIGHT = 1
OBESE = 2

DEFAULT_DATA_PATH = 'data'
ORIGINAL_IMAGE_FORMAT = re.compile('^([A-Z]\d+)_(\d+)_(\d+)\.jpg$')

TRAINED_MODEL_EXT = '.dat'
TRAINED_MODEL_FORMAT = "{}" + TRAINED_MODEL_EXT
